name: Landing Site Testing

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: english_landing
        type: choice
        options:
          - english_landing
          - spanish_landing
          - german_landing
          - hindi_landing
          - italian_landing
          - korean_landing
          - polish_landing
          - portuguese_landing
          - russian_landing
          - turkish_landing
          - ukrainian_landing
          - all_landings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "all_landings" ]; then
            pytest test_cases/ --alluredir=allure-results
          else
            pytest "test_cases/test_${{ github.event.inputs.deployment_target }}.py" --alluredir=allure-results
          fi
