
on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose target
          required: true
          default:
          type: choice
          options:
            - English landing
            - Spanish landing


jobs:
  test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: Install Dependencies
              run: pip install -r requirements.txt
            - name: english_landing
              if: "github.event.inputs.deployment_target == 'english_landing"
              run: pytest test_cases/test_english.py::test_open_website_english
            - name: spanish_landing
              if: "github.event.inputs.deployment_target == 'spanish_landing"
              run: pytest test_cases/test_english.py::test_how_it_works_english_page